language: elixir
elixir:
  - 1.4.0
  - 1.3.4
  - 1.3.3
  - 1.3.2
  - 1.3.1
  - 1.3.0
  - 1.2.6
  - 1.2.5
  - 1.2.4
  - 1.2.3
  - 1.2.2
  - 1.2.1
  - 1.2.0
  - 1.1.1
  - 1.1.0
  - 1.0.5
  - 1.0.4
otp_release:
  - 19.2
  - 19.1
  - 19.0
  - 18.3
  - 18.2
  - 18.1
  - 18.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq rhino
env:
  - EXECJS_RUNTIME=Node
  - EXECJS_RUNTIME=Rhino
